
== 回应“在中国IE就是浏览器的代名词”
posted 17 Aug 2010, 21:55 by HowHui Liew

针对“在中国IE就是浏览器的代名词”，我这样评论：
因为IE太容易嵌入木马、病毒了，所以中国所有公司、政府都特别喜欢它，不然，这些机构如何嵌入木马或病毒？偏偏中国的许多软件就是这样赚钱的，譬如网上电影QVod。我尝试用Wine来安装，用的时候就会出现DLL的错误。为什么？就是因为QVod 用自己的DLL取代系统的DLL。不然，一个软件只用普通的网络通信API如何获取我的电脑的资料？所以老百姓的无知继续支撑IE。


== 电脑出问题
posted 31 Jul 2010, 12:19 by HowHui Liew   [ updated 31 Jul 2010, 12:30 ]

今天电脑忽然出问题。当我启动电脑的时候，忽然听到电脑只连续发出“哔”的声音。着实把我吓了一条，心想，昨天的工作都泡汤了。本来以为硬盘或显卡的问题，结果利用旧电脑（我的旧电脑还可以用，而新电脑却这么容易出问题，可见虽然大家都在吹环保，商家却只关心卖不耐的东西，好有生意做）上网一查，ABIT的主板连续发出“哔”的声音可能是内存出了问题。我想反正电脑都不行了，就把内存弄一下，结果一开机居然可以了。所以有时候，我们必须有两台电脑，一台坏了，可以利用另一台上网查找原因，这样可以不用花钱去买一台三年以后就变成垃圾的新电脑。

其实我的Arch Linux昨天突然出现Kernel Dump的情况，我应该有所警觉，我太大意了。如果昨天就做资料备份，今天就不会大惊失色。所以电脑必须经常备份。


== Linux 汉化或国际化
posted 17 Jul 2010, 20:44 by HowHui Liew

尝试了一下 Gentoo，觉得这个版本对国际化的支持是很糟糕的。试想，我 emerge rxvt-unicode 本来是想看中文的。结果居然都是 ASCII！不知道是不是因为美国人在管理 gentoo，所以根本不关心国际化问题。我自己根据源代码编译后就可以看中文了。美国人这是想干什么，他们难道还真以为英文能走遍天下不成？傻B!

目前为止对我而言，设计得最好的 Linux 版本还是 Arch Linux。其次才是 Ubuntu。


== 可恶的 Adobe
posted 30 Jun 2010, 20:56 by HowHui Liew

也不知道要骂那些不懂电脑的文书工作人员还是 Adobe。不过，我还是觉得骂 Adobe 比较合理，因为这间公司的 Acrobat Reader 缺省打印使用 "Shrink to Printable Area"。有多少人知道什么是 Printable Area？这原来是打印机因为墨盒的限制无法在 A4 纸的旁边打印，只能在纸的 94% 地方打印，所有像我这种使用 PDF 打印的人，常常面对文书工作的人把 PDF 印小了一点的苦恼。可恶的软件公司就是不会为不懂软件的人着想的，所有电子化办公谈何容易！


== 甭买戴尔电脑(Don't buy from Dell)
posted 28 Jun 2010, 22:38 by HowHui Liew   [ updated 28 Jun 2010, 22:42 ]

看来 Dell 只会做大企业的生意，只在昂贵的服务器上装 Linux 而在个人电脑或笔记本上就服务极其糟糕！见 http://www.qtrac.eu/dont-buy-dell.html

