== 一点电脑的学习
posted 28 Apr 2011, 20:35 by HowHui Liew   [ updated 28 Apr 2011, 20:39 ]

. 2008-11-19: M$Win 居然无法阅读有两个FAT分区的U-盘，实在岂有此理。所 以，问题并不出在fdisk。然而，在Linux下的syslinux仍然有问题，在WinXP下 用syslinux -ma f:才让U-盘能正式启动。
. 2008-10-25: 尝试用 abcl-0.0.11 编译有线程功能的 sbcl-1.0.21，结果出 现编译错误。还以为是 abcl-0.0.11 的问题，于是决定用 abcl-0.0.10。把 sbcl-1.0.21 删除后，从新解压 sbcl-1.0.21 后忘了添加线程功能，结果用 abcl-0.0.10 编译就不出问题。可是，再次添加线程功能发现就发现同样的 错误：

    java.lang.VerifyError: (class: org/armedbear/lisp/thread_66,
    method: execute signature: (Lorg/armedbear/lisp/LispObject;
    Lorg/armedbear/lisp/LispObject;)Lorg/armedbear/lisp/LispObject;)
    Inconsistent stack height 1 != 3

. 得用 sbcl 编译有线程功能的自己才没有问题。
+
--
我在 2003 年的时候发现博客这东西，当时还不知道如何在 GNU/Linux 下输入 中文，所以用英文输入。如今，我能很方便地在 GNU/Linux 输入中文了。这得 感谢 XSIM 输入法的作者 (http://sourceforge.net/projects/xsim/)、自由软 件基金(FSF)、Redhat 公司（我仍然使用着 Redhat 9.0）以及许许多多在网上 讲解如何将汉化 GNU/Linux 的人们。

当年我刚毕业不久，趁失业期间上网学习电脑知识，同时希望能够学到能用于整 理百科全书的知识。可惜，我在读大学期间与电脑世界隔绝了那么久，为了弥补 自己的电脑知识，我在失业期间把精力都集中于学习电脑方面的知识，忽略了科 学方面的学习（找到工作后有没有时间学习，这就是人生的无奈）。当然，我始 终没有忘记自己学习电脑就是为了整理出自己的一套百科全书。

然而，我却发现 Wales 和 Sanger 居然在 2001 年已经创建了属于全世界的百 科全书－－维奇百科。这实在让我为自己的“多说不做”感到惭愧。然而，我也为 世界有为知识（包括软件）的传播与共享的人而感到高兴和激动。

我也希望能为知识的共享而努力。然而世界各国为了商家们的利益，开始设置各 种知识产权法令，这可能让“知识”被某些大公司垄断，这不尽令我担心大公司通 过“知识产权”控制世界。
--

== 推荐文章
posted 28 Apr 2011, 20:34 by HowHui Liew

It's not the Gates, it's the bars

商业最重要的精神应该是服务。而为了鼓励服务质量的提高，最重要是鼓励 竞争。可是，微软做的事情就是垄断，而许多人不自觉的鼓励垄断。结果就 是社会成本的提高与经济效率的降低。

Foxconn deliberately sabotaging their BIOS to destroy Linux ACPI

为什么我那么痛恨微软？这难道不是微软与某些硬件厂商勾结，好让Linux支 持变得困难的方式。为什么故意在BIOS中故意检查到Linux然后破坏ACPI？


== 老师的告白
posted 28 Apr 2011, 19:12 by HowHui Liew

对《有房出租》第六集的《老师的告白》特别有感触：今天香港的教育弄出什么《其它学习经验》（OLE）和《通适教育》，为了让学校很好的生存，教师还必须做许多行政工作，教育的工作忽然变得很压力，结尾的感叹特别有意思：如今弄出那么多莫名其妙的学科，难道比起以前更能教出好学生？以前的教育很简单，只要教会学生做人道理就行了。


== 遗失在奥斯丁的世界
posted 6 Apr 2011, 20:37 by HowHui Liew

人生常常会碰到惊喜，2011.4.6 居然在 Astro 735 看到《Loss in Austen》这个根据傲慢与偏见编写的短剧。相比起中国如今流行的回到古代的连续剧，这样类型的具有文艺性质的戏剧更吸引我。


== 最贵的车
posted 4 Mar 2011, 22:08 by HowHui Liew

看第 16 期第 6 集的 Top Gear 才知道世界上最贵的车居然是美国送上月亮的月球车。当时 1960 年代就价值两千万美元（算上通货膨胀等因素，这车当今要上亿）。


