= 经济与环保 (Environmental Protetion)

== 电子设备的环保
** 怀了的电子设备必需可以修理，我们的世界才不会不断的产生电子垃圾。
*** 支持 https://www.youtube.com/watch?v=8XN98T0KLGI[RIGHT TO REPAIR]
** 用太多电子设备的机构其实是不环保的。


== P. Piketty 的 21 实际资本论 (精句)

https://piketty.pse.ens.fr/capital21c

p85: Charles Dunoyer (1845) 的《De la liberte du Travail》:
"工业体系的影响之一就是摧毁人为的不平等（身份，地位），但这只是更加
清楚地凸显了自然的不平等"

p116: "寻租" （arbitrage ?)

p219: 资本过多会扼杀资本的回报 （很好的说明我们目前的世界）

p250: 如果你继承了一套公寓并因此节省了房租费用，你将更容易通储蓄累积财富

p280: 1914~1945 (一战，二战）对资本的冲击降低了前 10% 人群收入的比重，
最终导致收入不平等显著缩小。

问： IHS Markit, Bloomberg, Google 等的"信息"垄断算吗？

p335: 我注意到，1990年以后，税收数据的获取在一定程度上变得更加难了。
部分原因在于计算机时代的到来，税务部门中断了对详细税收统计数据的发布，...

p457: 创业者会变成食利者，不仅是在代际交接过程中，在同一代人中也会出现，
尤其是当人均寿命不断延长的今天。

p458: 这中对盖茨的顶礼膜拜反映了现代民主社会需要将贫富差距合理化的不可
遏制的需求。

p465: 基金规模越大可实现的收益就越高，进而导致资本收益上的明显的不平等。
这些高额回报很大程度上造就了美国著名高校的长盛不衰。来自校友的新捐赠额
反而有限，每年校友的新捐赠仅相当于学校基金会投资回报额的 1/10 ～ 1/5.

p479: 为何发达国家之众会有这样荒谬的担忧，会担心自己的国家财富落入他国
之手？部分原因无疑是那种以嫁接外国人来缓解国内矛盾的普通情绪。

总结：资本收益 r > 生产收益 g, 社会财富分配就危险。


== W. Arthur Lewis (1978) 的《增长与波动》(精句)

p179: 学院式的科学对工业革命几乎没有作出什么贡献，而且，直到 1880 年
以后，它也还没有与工业工艺结合起来 ... 在十九世纪最后二十五年，德国已
在科学与工业之间架起了桥梁，而英国还没有这样做。

p193: 受过教育比没受过教育要好，但是，更多的正规教育并不一定能生产
更多的工业产量。

p263: 这些国家毫不犹豫地对这些土著人发动战争，屠杀他们，或把他们限制
在居住地內，以便使大片的土地可以交给欧洲人耕种。



