WEBROOT=../../liaohaohui.github.io

all:
	#asciidoctor index.adoc -o ${WEBROOT}/index.html
	##asciidoctor UECM1703/README.adoc -o ${WEBROOT}/UECM1703/index.html
	##-cp s01_basic.pdf p01_basic.pdf ${WEBROOT}/UECM1703/
	##-cp s02_array.pdf p02_array.pdf p03_adv.pdf ${WEBROOT}/UECM1703/
	##-cp UECM1703-test.pdf ${WEBROOT}/UECM1703/
	##-cp ${WEBROOT}/UECM1703/
	asciidoctor UECM3993/README.adoc -o ${WEBROOT}/UECM3993/index.html
	asciidoctor IndSciU/README.adoc -o ${WEBROOT}/IndSciU/index.html
	asciidoctor IndSciU/CompSci/README.adoc -o ${WEBROOT}/IndSciU/CompSci/index.html
	asciidoctor IndSciU/CompSci/operating_system.adoc -o ${WEBROOT}/IndSciU/CompSci/operating_system.html

