WEBROOT=../../liaohaohui.github.io

all:
	asciidoctor index.adoc -o ${WEBROOT}/index.html
	#asciidoctor UECM3584.adoc -o ${WEBROOT}/UECM3584/index.html
	#asciidoctor UECM3594.adoc -o ${WEBROOT}/UECM3594/index.html
	##asciidoctor UECM1703/README.adoc -o ${WEBROOT}/UECM1703/index.html
	##-cp s01_basic.pdf p01_basic.pdf ${WEBROOT}/UECM1703/
	##-cp s02_array.pdf p02_array.pdf p03_adv.pdf ${WEBROOT}/UECM1703/
	##-cp UECM1703-test.pdf ${WEBROOT}/UECM1703/
	##-cp ${WEBROOT}/UECM1703/
	#asciidoctor UECM3993/README.adoc -o ${WEBROOT}/UECM3993/index.html
	#asciidoctor UECM1303.adoc -o ${WEBROOT}/UECM1303/index.html
	#asciidoctor IndSciU/README.adoc -o ${WEBROOT}/IndSciU/index.html
	#asciidoctor IndSciU/CompSci/README.adoc -o ${WEBROOT}/IndSciU/CompSci/index.html
	#asciidoctor IndSciU/CompSci/operating_system.adoc -o ${WEBROOT}/IndSciU/CompSci/operating_system.html
	#asciidoctor IndSciU/Math/README.adoc -o ${WEBROOT}/IndSciU/Math/index.html
	#asciidoctor IndSciU/Math/Calculus/README.adoc -o ${WEBROOT}/IndSciU/Math/Calculus/index.html
	#asciidoctor IndSciU/Math/ComplexAnal/README.adoc -o ${WEBROOT}/IndSciU/Math/ComplexAnal/index.html
	#asciidoctor IndSciU/Math/DiscreteMath/README.adoc -o ${WEBROOT}/IndSciU/Math/DiscreteMath/index.html
	#asciidoctor IndSciU/Math/LinearAlgebra/README.adoc -o ${WEBROOT}/IndSciU/Math/LinearAlgebra/index.html
	#asciidoctor IndSciU/Math/NumberTheory/README.adoc -o ${WEBROOT}/IndSciU/Math/NumberTheory/index.html
	#asciidoctor IndSciU/Math/ProbStat/README.adoc -o ${WEBROOT}/IndSciU/Math/ProbStat/index.html
