# https://9p.io/magic/webls?dir=/sources/contrib/quanstro/ttf2subf
ttf2subf:
	gcc -I${PLAN9}/include -I/usr/include/freetype2/ ttf2subf.c -lfreetype -L/home/liaohaohui/zTmp/zSrc/OS/plan9port/lib -lmemdraw -ldraw -l9 -o ttf2subf

#./ttf2subf -s 18 -f /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc -n NotoSansCJK-Regular -m antialias
#./ttf2subf -s 16 -f /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc -n NotoSansCJK-Regular -m mono
